### ISSUE TITLE
My game crashes everytime I open the icon kit

### ISSUE THREAD

**Issue by Epyx15** [nytelytee/geode-garage-utilities#1] opened 2024-05-10 21:31 UTC
Idk if it's happening because I'm playing on an android device with 64 bits, or if the mod is incompatible with another mod I have

**Comment by nytelytee** [comment] 2024-05-11 16:13
There has been another bug report about this crashing before, but I was never able to reproduce it, so if you can narrow down your mod list and still repro, it would really help.

**Comment by nytelytee** [comment] 2024-05-17 00:53
Correction: my previous comment assumed that these were the same bug, but they don't seem to be, the icon kit crashes for me on Android as well now. Still not sure what the cause is, however.

**Comment by nytelytee** [comment] 2024-05-28 17:24
Should be fixed in v1.0.5.

**Closed as completed** 2024-05-28 17:24 UTC
